name: build
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{
        fromJSON( '{"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}' )
        }}
    steps:
      - run: echo ${{ matrix.project }} "/" ${{ matrix.config }}
