name: build
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix: >-
        ${{
          fromJSON(
            1 == 1
            && format('{{"include":[{{"project":"{0}","config":"Debug"}},{{"project":"{1}","config":"Release"}}]}}', 'foo', 'bar')
            || '{include:[{"project":"foobar","config": "trace"}]}'
          )
        }}
    steps:
      - run: echo ${{ matrix.project }} "/" ${{ matrix.config }}
