name: build
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{
          fromJSON(
            format('{{"include":[{{"project":"{0}","config":"Debug"}},{{"project":"{1}","config":"Release"}}]}}', 'foo', 'bar')
          )
        }}
    steps:
      - run: echo ${{ matrix.project }} "/" ${{ matrix.config }}
